[profile.default]
src = "src"
solc-version = "0.8.26"
optimizer = true
optimizer-runs = 10_000_000
out = "out"
libs = ["lib"]
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options

# --snip--
[rpc_endpoints]
mainnet = "${MAINNET_RPC_URL}" 
